# Generated by Django 2.1.5 on 2019-05-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='typeExercise',
            field=models.IntegerField(default=1),
        ),
    ]
